dataset_name: "glue_v002_proportional" # "glue_v002_proportional" # "glue_stsb_v002"
split: "train" # validation
input_seq_len: 128
target_seq_len: 20
batch_size: 48
use_iterable_ds: True
val_split_name: "validation"