run_training: True
run_evaluation: True
seed: 12345
eval_every: 100

# Multi-host
distributed:
  kwargs:
    backend: "GLOO" # use NCCL for GPU
    rank: 0
    world_size: 1

dataset_name: "c4.en" # "glue_cola_v002"
split: "train"
input_seq_len: 512
target_seq_len: 128
batch_size: 16 # per device
use_iterable_ds: True

#dataset:
#  kwargs:
#    name: "glue_v002_proportional" # "glue_cola_v002"
#    split: "validation"
#    max_seq_length: 32
#    batch_size: 4
#    use_iterable_ds: True

# Optimizer
optim:
  name: "Adafactor"
  kwargs:
    clip_threshold: 1.0
    decay_rate: -0.8
    weight_decay: 0.0
    relative_step: True
    scale_parameter: True
    warmup_init: True


# Steps
training:
  checkpoint_every: 1000

# Steps
wandb:
  log_scalars_every: 20

num_train_steps: 10000

# Logging
use_wandb: True

# Model Config
model_config:
  d_ff: 3072
  d_kv: 64
  d_model: 768
  decoder_start_token_id: 0
  dropout_rate: 0.1
  eos_token_id: 1
  feed_forward_proj: "relu"
  gradient_checkpointing: "False"
  initializer_factor: 1.0
  is_encoder_decoder: "True"
  layer_norm_epsilon: 1e-6
  model_type: "t5"
  num_decoder_layers: 12
  num_heads: 12
  num_layers: 12
  pad_token_id: 0
  relative_attention_num_buckets: 32
  transformers_version: "4.10.0.dev0"
  use_cache: false
  cache_dir: "/tmp/"
  vocab_size: 32003


tpu:
  kwargs:
    zone: "europe-west4-a"
    network: "tpu-network"
    subnet: "swarm-2"
    netrange: "192.170.0.0/29"
    acc_type: "v3-8"
    preemptible: False
    bucket: "must-results-europe"
    project: "polytax"
job:
  kwargs:
    env_stmts: ["export XRT_TPU_CONFIG='localservice;0;localhost:51011';", "export PATH=$PATH:/home/$USER/.local/bin;", "unset LD_PRELOAD;"]
    setup_cmds: ["cd ~/polytax/ && git pull origin master", "pip uninstall -y wormulon", "pip install git+https://git@github.com/mweiss17/wormulon@main#egg=wormulon", "pip uninstall -y transformers", "pip install git+https://github.com/Arka161/transformers@master#egg=transformers", "cd ~/polytax/ && pip install -e .[xla]"]
    install_cmd: "cd ~/; git clone https://github.com/mweiss17/polytax.git; pip uninstall -y wormulon; pip install -e polytax[xla];"
    train_cmd: "python3 ~/polytax/src/polytax/train.py"
    cleanup_cmd: "pkill -9 python3"